image: metasolutions/openjdk-node:latest

stepdefinitions:
  - build: &build
      name: Build
      script:
#        - if [ $BITBUCKET_BRANCH != "master" ] && [ $BITBUCKET_BRANCH != "develop" ]; then exit 0 ; fi
        - node --version
        - npm --version
        - yarn --version
        - yarn cache dir
        - export ES_VERSION=`jq -r .version package.json`
        - echo $ES_VERSION
        # We allow anything between x.y and x.y.z-SNAPSHOT
        - if [ ${#ES_VERSION} -lt 3 ] || [ ${#ES_VERSION} -gt 14 ]; then exit 1 ; fi
        - yarn
        - yarn upgrade rdforms esi18n rdfjson store
        - yarn build:suite
        - echo $ES_VERSION > src/app/suite/dist/VERSION.txt
        - yarn build:registry
        - echo $ES_VERSION > src/app/registry/dist/VERSION.txt
      artifacts:
        - src/app/**
      caches:
        - node
        - yarncustom
  - deploy: &deploy
      name: Deploy
      script:
        - export ES_VERSION=`jq -r .version package.json`
        # We allow anything between x.y and x.y.z-SNAPSHOT
        - if [ ${#ES_VERSION} -lt 3 ] || [ ${#ES_VERSION} -gt 14 ]; then exit 1 ; fi
        - ( cd src/app/suite/dist && rsync -arz --delete * "deploy@meta3.metasolutions.se:/srv/static.entryscape.com/suite/$ES_VERSION/" )
        - if [ $BITBUCKET_BRANCH == "develop" ]; then ssh deploy@meta3.metasolutions.se "cd /srv/static.entryscape.com/suite; rm latest; ln -s $ES_VERSION latest" ; elif [ $BITBUCKET_BRANCH == "master" ]; then ssh deploy@meta3.metasolutions.se "cd /srv/static.entryscape.com/suite; rm stable; ln -s $ES_VERSION stable" ; fi
        - ( cd src/app/registry/dist && rsync -arz --delete * "deploy@meta3.metasolutions.se:/srv/static.entryscape.com/registry/$ES_VERSION/" )
        - if [ $BITBUCKET_BRANCH == "develop" ]; then ssh deploy@meta3.metasolutions.se "cd /srv/static.entryscape.com/registry; rm latest; ln -s $ES_VERSION latest" ; elif [ $BITBUCKET_BRANCH == "master" ]; then ssh deploy@meta3.metasolutions.se "cd /srv/static.entryscape.com/registry; rm stable; ln -s $ES_VERSION stable" ; fi

pipelines:
  default:
    - step: *build
  branches:
    master:
      - step: *build
      - step: *deploy
    develop:
      - step: *build
      - step: *deploy
    feature/*:
      - step: *build

definitions:
  caches:
    yarncustom: /usr/local/share/.cache/yarn/
