image: metasolutions/openjdk-node:latest

pipelines:
  default:
    - step:
        script:
          - if [ $BITBUCKET_BRANCH != "master" ] && [ $BITBUCKET_BRANCH != "develop" ]; then exit 0 ; fi
          - node --version
          - npm --version
          - mkdir -p ~/.ssh
          - echo $SSH_KNOWN_HOSTS >> ~/.ssh/known_hosts
          - ( umask 077 ; echo $SSH_KEY | base64 --decode --ignore-garbage > ~/.ssh/id_rsa )
          - export ES_VERSION=`jq -r .version bower.json`
          - echo $ES_VERSION
          # We allow anything between x.y and x.y.z-SNAPSHOT
          - if [ ${#ES_VERSION} -lt 3 ] || [ ${#ES_VERSION} -gt 14 ]; then exit 1 ; fi
          - bower install --allow-root
#          - ( cd build && ./build.sh )
#          - ( cd release && rsync -arz --delete * "deploy@meta1.metasolutions.se:/var/www/entrystore.org/js/$ESJS_VERSION/" )
#          - if [ $BITBUCKET_BRANCH == "develop" ]; then ssh deploy@meta1.metasolutions.se "cd /var/www/entrystore.org/js/; rm latest; ln -s $ESJS_VERSION latest" ; elif [ $BITBUCKET_BRANCH == "master" ]; then ssh deploy@meta1.metasolutions.se "cd /var/www/entrystore.org/js/; rm stable; ln -s $ESJS_VERSION stable" ; fi
