image: metasolutions/openjdk-node:latest

options:
  max-time: 12

stepdefinitions:
  - build: &build
      name: Build
      script:
#        - if [ $BITBUCKET_BRANCH != "master" ] && [ $BITBUCKET_BRANCH != "develop" ]; then exit 0 ; fi
        - node --version
        - npm --version
        - yarn --version
        - yarn cache dir
        - export ES_VERSION=`jq -r .version package.json`
        - echo $ES_VERSION
        # We allow anything between x.y and x.y.z-SNAPSHOT
        - if [ ${#ES_VERSION} -lt 3 ] || [ ${#ES_VERSION} -gt 14 ]; then exit 1 ; fi
        - yarn
#        - yarn upgrade rdforms esi18n rdfjson store # deactivated because we don't cache anymore
        - yarn build:suite
        - echo $ES_VERSION > src/app/suite/dist/VERSION.txt
        - yarn build:registry
        - echo $ES_VERSION > src/app/registry/dist/VERSION.txt
        # We check whether the sizes of the builds are below 3.5MB (probably needs to be raised in the future)
        - if [ `wc -c < src/app/suite/dist/app.js` -gt 3500000 ]; then exit 1 ; fi
        - if [ `wc -c < src/app/registry/dist/app.js` -gt 3500000 ]; then exit 1 ; fi
      artifacts:
        - src/app/**
#      caches:
#        - node
#        - yarncustom
  - deploy: &deploy
      name: Deploy
      script:
        - export ES_VERSION=`jq -r .version package.json`
        # We allow anything between x.y and x.y.z-SNAPSHOT
        - if [ ${#ES_VERSION} -lt 3 ] || [ ${#ES_VERSION} -gt 14 ]; then exit 1 ; fi
        - ( cd src/app/suite/dist && rsync -arvz --delete-after . "deploy@meta9.metasolutions.se:/srv/static.infra.entryscape.com/suite/$ES_VERSION/" )
        - if [ $BITBUCKET_BRANCH == "develop" ]; then ssh deploy@meta9.metasolutions.se "cd /srv/static.infra.entryscape.com/suite; rm -r latest; ln -s $ES_VERSION latest" ; elif [ $BITBUCKET_BRANCH == "master" ]; then ssh deploy@meta9.metasolutions.se "cd /srv/static.infra.entryscape.com/suite; rm -r stable; ln -s $ES_VERSION stable" ; fi
        - ( cd src/app/registry/dist && rsync -arvz --delete-after . "deploy@meta9.metasolutions.se:/srv/static.infra.entryscape.com/registry/$ES_VERSION/" )
        - if [ $BITBUCKET_BRANCH == "develop" ]; then ssh deploy@meta9.metasolutions.se "cd /srv/static.infra.entryscape.com/registry; rm -r latest; ln -s $ES_VERSION latest" ; elif [ $BITBUCKET_BRANCH == "master" ]; then ssh deploy@meta9.metasolutions.se "cd /srv/static.infra.entryscape.com/registry; rm -r stable; ln -s $ES_VERSION stable" ; fi
  - deploybranch: &deploybranch
      name: Deploy branch
      script:
        - ( cd src/app/suite/dist && rsync -arvz --delete-after . "deploy@meta9.metasolutions.se:/srv/static.infra.entryscape.com/_branches/${BITBUCKET_BRANCH#*/}/" )


pipelines:
  default:
    - step: *build
  branches:
    master:
      - step: *build
      - step: *deploy
      - step: *deploybranch
    develop:
      - step: *build
      - step: *deploy
      - step: *deploybranch
    feature/*:
      - step: *build
      - step: *deploybranch

#definitions:
#  caches:
#    yarncustom: /usr/local/share/.cache/yarn/
